#
# USB armory Mk II board Makefile
# https://github.com/inversepath/usbarmory
#
# Copyright (C) 2019, F-Secure
# Andrej Rosano <andrej.rosano@f-secure.com>
#
# SPDX-License-Identifier:|____GPL-2.0+

obj-y	:= usbarmory-mark-two.o
